### ISSUE TITLE
建議移除繁簡轉換開關

### ISSUE THREAD

**Issue by Ivan-Kozlov-2012** [ensigma96/rime-nihongo-hybrid#2]
```
  - name: jp_variants
states: [ Trad, Simp ]

```
這部分感覺對日語輸入法不太適用？

**Comment by ensigma96** [comment]
這個開關的用途是日本 [新、舊字形](https://en.wikipedia.org/wiki/Ky%C5%ABjitai#Ky%C5%ABjitai_vs._Shinjitai) 轉換。參閱本方案中
```
simplifier:
  option_name: jp_variants
  opencc_config: jp_t2s.json
```
這三行，可以發現相應的 OpenCC 配置文件叫 jp_t2s.json。它和它引用的 OpenCC 字典 JPVariants.ocd 均位於本倉庫的 `dist/opencc/` 下，需要將兩者一併放入 Rime 用戶目錄下的 `opencc/` 文件夾（如果沒有，則創建一個）纔能工作。

此外，當開關處於 `Trad` 狀態時，顯示的候選實際上是 dict 中未轉換的內容。由於本方案的辭典中新舊字體均有，這時的候選也並不全是舊字體；而僅能使得處於 `Simp` 狀態時的候選是新字體。例如輸入 「sakura」，在 `Trad` 狀態下的候選既有「桜」，也有「櫻」；在 `Simp` 狀態下則只有「桜」。
